#! /usr/bin/env bash

set -u
set -e
set -o pipefail

[ "${DEBUG:-}" == "debug" ] && set -x

dir_resolve()
{
	cd "$1" 2>/dev/null || return $?
	echo $(pwd -P)
}

PASSWORD_ENTRY=${1:-}

recipients_search_path=$(dir_resolve $(dirname "$PASSWORD_ENTRY"))
recipients_file="/dev/null"
while [ "$recipients_search_path" != "/" ]
do
        if [ -f "$recipients_search_path"/.sciolist-recipients ]
	then
		recipients_file="$recipients_search_path"/.sciolist-recipients
		break
	fi
        recipients_search_path=$(dirname "$recipients_search_path")
done

[ "$recipients_file" != "/dev/null" ] || exit 110

RECIPIENTS_FILE="$recipients_search_path"/.sciolist-recipients
RECIPIENTS="$(awk '{print "-r " $1}' < "$RECIPIENTS_FILE")"

mkdir -p $(dirname "$PASSWORD_ENTRY")
exec gpg -s -a -e "$RECIPIENTS" -o "$PASSWORD_ENTRY" /dev/stdin
